### ISSUE TITLE
运行了之后出现一点问题

### ISSUE THREAD

**Issue by TrevoryZhou** [royJang/iSystem#1]
非专业人士。。Mac os 最新的10.11系统
安装之后运行npm install isystem -g 出现下面的错误提示，还有一个安装成功的文件列表吧，您给看看出现了什么问题呢？

npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
/usr/local/lib
└─┬ isystem@0.4.9
  ├─┬ cheerio@0.19.0
  │ ├─┬ css-select@1.0.0
  │ │ ├── boolbase@1.0.0

（这个下面还有好多，我就不复制了，列表结束后就是下面的错误提升了）

npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "isystem" "-g"
npm ERR! node v4.2.1
npm ERR! npm  v3.3.9
npm ERR! path /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, access '/usr/local/lib/node_modules']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/zhoubo/npm-debug.log

**Comment by fun5rt** [comment]
忘记说了，我的是Mac os系统

**Comment by royJang** [comment]
使用sudo运行了吗，可以试一试sudo isystem。

**Comment by TrevoryZhou** [comment]
解决了，上面的错误原来是npm权限的问题。

目前安装好了，打开 http://localhost:3005/ 后需要手动复制其中内容替换到系统中的hosts么？

**Comment by royJang** [comment]
不需要的，自动替换到hosts上的。由于系统权限的问题， 可能无法写入系统hosts，需要用sudo isystem运行，赋予它权限。
