### ISSUE TITLE
使用问题。

### ISSUE THREAD

**Issue by TrevoryZhou** [royJang/iSystem#2]
安装好了isystem，前几天测试成功了

不过今天想要再次使用，打开3005网页就无法显示了。
运行结果如下：
iSystem listen at http://localhost:3005
/usr/local/lib/node_modules/isystem/node_modules/jsonfile/index.js:38
      throw err
      ^

SyntaxError: /Applications/isystem/.DS_Store: Unexpected token

**Comment by royJang** [comment]
可能是分组文件出错导致，使用isystem -c 先清除分组文件。然后重新获取。有些麻烦，建议修复问题后升级到最新版本。如有重现随时联系我。^_^

**Comment by TrevoryZhou** [comment]
使用isystem -c之后就可以打开了

On November 4, 2015 at 15:48:16, roy (notifications@github.com) wrote:

可能是分组文件出错导致，使用isystem -c 先清除分组文件。然后重新获取。有些麻烦，建议修复问题后升级到最新版本。如有重现随时联系我。^_^

**Comment by TrevoryZhou** [comment]
还有一个问题，如果是使用这个保存的话，我的hosts的格式会变动，你的有这个问题嘛

**Comment by royJang** [comment]
更新到0.4.11应该不会有这个问题了。。不过还是会对hosts格式做一些修改，不会影响使用。

**Comment by TrevoryZhou** [comment]
怎么更新呢？是重新安装么？还是有什么isystem -update的命令呢？

**Comment by royJang** [comment]
用npm更新 npm update -g isystem
